### PR TITLE
adapt to latest kernel 5.6.x

### PR DESCRIPTION
**Pull request by tpgxyz**
with this PR uksm-5.6.patch applies cleanly to 5.6.12 kernel
@dolohow ping

### CODE REVIEW

**Comment by dolohow** [comment]
Your patch does not apply cleanly on v5.6

**Comment by bruce-one** [comment]
I think this is no longer required due to #61 being merged (because this is modifying the context which was removed by #61).

**Comment by tpgxyz** [comment]
@dolohow It does apply cleanly on 5.6.12 as there were modifications in upstream :)

**Comment by dolohow** [comment]
@tpgxyz Can you confirm that current version of `5.6` applies on `5.6.12`?

**Comment by tpgxyz** [comment]
@dolohow your current uksm-5.6.x.patch does NOT apply to kernel 5.6.12.
See here https://github.com/OpenMandrivaAssociation/kernel-release-clang/commit/9c017fe9a3db051ce30ab34fcecc35425c072523

**Pull request closed without merging**
