### PR TITLE
Resync for linux-5.18.y

### PR DESCRIPTION
**Pull request by sirlucjan**
Port for kernel 5.18 - simple adaptation to upstream changes. I will make adjustments as necessary. 
Signed-off-by: Piotr Gorski <lucjan.lucjanov@gmail.com>

### CODE REVIEW

**Comment by sirlucjan** [comment]
It's not working properly, so I'm closing PR. I've been using UKSMD for a while now, and I don't know if I can find the will and motivation to keep porting. @dolohow Thanks a lot for your cooperation so far.

**Comment by bhzhu203** [comment]
Is UKSMD better than uksm kernel ? @sirlucjan

**Comment by sirlucjan** [comment]
It's certainly less problematic. I ported versions 5.16 and 5.17 and I assure you it was neither easy nor fun. The folio mechanism introduces a lot of changes and with 5.18 you would have to rewrite a lot of code. I simply do not have the will or time for that. UKSMD works at least as well. With UKSMD there were also various kinds of crashes, which were reported from time to time. I never had enough time to sit down and rewrite the code to make it work with the latest kernel mechanisms. I just wanted it to compile properly and work reasonably well. UKSMD is much smaller than UKSM, it is based on a slightly different mechanism and most importantly it is actively developed by the pfkernel developer. UKSMD is also included in zenkernel so it is becoming more widely used. Personally I am very happy with UKSMD and I do not see even the slightest chance to go back to UKSM.

**Comment by bhzhu203** [comment]
> It's certainly less problematic. I ported versions 5.16 and 5.17 and I assure you it was neither easy nor fun. The folio mechanism introduces a lot of changes and with 5.18 you would have to rewrite a lot of code. I simply do not have the will or time for that. UKSMD works at least as well. With UKSMD there were also various kinds of crashes, which were reported from time to time. I never had enough time to sit down and rewrite the code to make it work with the latest kernel mechanisms. I just wanted it to compile properly and work reasonably well. UKSMD is much smaller than UKSM, it is based on a slightly different mechanism and most importantly it is actively developed by the pfkernel developer. UKSMD is also included in zenkernel so it is becoming more widely used. Personally I am very happy with UKSMD and I do not see even the slightest chance to go back to UKSM.

Is there PF kernel patch for 5.18? Because the bcachefs kernel modules create their 5.18 tree , I have no way to patch UKSM. Maybe I can try the UKSMD (PF kernel) with  latest bcachefs kernel modules : ) .   Thanks

**Comment by sirlucjan** [comment]
Yes, you can find everything in pfkernel without any problem.

**Pull request closed without merging**
